name: Normans rant's
title: Normans rant's and more
org: Organization
base_url: '/blog.normanmaurer.me/'

profiles:
  production:
    base_url: http://normanmaurer.github.io/blog.normanmaurer.me
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: gh-pages
      # use master branch for <username>.github.io repository
      #branch: master
