name: Normans rant's
title: Normans rant's and more
google_analytics: UA-45259657-1


profiles:
  production:
    disqus: normanmaurer
    base_url: http://normanmaurer.me
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: gh-pages
      # use master branch for <username>.github.io repository
      #branch: master

  stagign:
    disqus: normanmaurer
    base_url: http://normanmaurer.github.com/blog.normanmaurer.me
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      #branch: gh-pages
      # use master branch for <username>.github.io repository
      branch: master
